M48
; DRILL file {KiCad 8.0.8} date 2025-03-09T17:06:26-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-09T17:06:26-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X84.582Y-44.45
X84.582Y-127.254
X214.884Y-44.196
X215.138Y-127.254
M30
